language: cpp
compiler: gcc
os: linux
dist: focal

env:
  global:
    - MAKEFLAGS="-j 2"

install:
  - sudo apt-get update
  - sudo apt install cmake libgtest-dev lcov rapidjson-dev libcurl4-openssl-dev -y
  - sudo apt install python3-numpy libtbb-dev libxxhash0 -y
  - pip install --user cpp-coveralls
  - wget gccb.if.uj.edu.pl/code/root-cpp17_6.22.08_amd64.deb
  - sudo dpkg -i root-cpp17_6.22.08_amd64.deb
  - . /etc/profile
  - root-config --cflags
  - root-config --features
  - cmake -S . -B build -DCODE_COVERAGE=On -DENABLE_TESTINGS=On -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS='--std=c++17'

script:
  - cmake --build build --config Release
  - cmake --build build --target test

after_success:
  - coveralls -i lib -i dst --gcov-options "-lp"
