language: cpp
compiler: gcc
os: linux
dist: focal
services:
  - docker

env:
  global:
    - MAKEFLAGS="-j 2"

before_install:
  - docker pull rootproject/root:6.22.06-conda
    docker run rootproject/root:6.22.06-conda
  - root-config --cflags
  - root-config --features

before_script:
  - sudo apt-get update
  - sudo apt-get install -y libcppunit-dev cmake lcov
  - mkdir build
  - cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS='--std=c++17'

script:
  - cmake --build build --config Release
  - cmake --build build --target test
