language: cpp
compiler: gcc
os: linux
dist: focal

env:
  global:
    - MAKEFLAGS="-j 2"

before_script:
    - sudo apt-get update
    - sudo apt-get install -y libcppunit-dev lcov
    - mkdir .aux_deps
    - wget https://root.cern/download/root_v6.22.06.Linux-ubuntu20-x86_64-gcc9.3.tar.gz
    - tar zxf root_v6.22.06.Linux-ubuntu20-x86_64-gcc9.3.tar.gz -C .aux_deps
    - . ./.aux_deps/root/bin/thisroot.sh
    - root-config --cflags
    - root-config --features
    - mkdir build && cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
script:
    - make
    - make test
